### ISSUE TITLE
Add flood protection

### ISSUE THREAD

**Issue by Moppy-cloud** [Squirrel-Network/nebula8#13]

**Comment by BluLupo** [comment]
@Moppy-cloud We will be working on this feature soon

**Comment by SteelManITA** [comment]
Add flood protection also for nebula messages:
if 20 users (bot) type /staff, nebula writes immediatly 20 messages, and telegram blocks nebulabot by "flood".

**Comment by TheLonelyAdventurer** [comment]
> Add flood protection also for nebula messages: if 20 users (bot) type /staff, nebula writes immediatly 20 messages, and telegram blocks nebulabot by "flood".

I think the problem is not replying. There is a workaround for that from the python-telegram-bot library.

I think the main issue is how to detect a flood storm.

The ideal way would be to compare the messages from the users.

I would make this kind of checks:

- Whether the same user writes the same thing 10+ times.
- Whether the same user writes too fast 10+ messages.
- Do not reply to commands if these conditions are met because the bot would hang up.
